#define TK_AND                             1
#define TK_AS                              2
#define TK_ASC                             3
#define TK_BY                              4
#define TK_CHECK                           5
#define TK_COMMA                           6
#define TK_COMMENT                         7
#define TK_CONSTRAINT                      8
#define TK_CREATE                          9
#define TK_DEFAULT                        10
#define TK_DELETE                         11
#define TK_DESC                           12
#define TK_DOT                            13
#define TK_DROP                           14
#define TK_END_OF_FILE                    15
#define TK_EQ                             16
#define TK_EXPLAIN                        17
#define TK_FIELD                          18
#define TK_FLOAT                          19
#define TK_FROM                           20
#define TK_FUNCTION                       21
#define TK_GE                             22
#define TK_GT                             23
#define TK_ID                             24
#define TK_ILLEGAL                        25
#define TK_INDEX                          26
#define TK_INSERT                         27
#define TK_INTEGER                        28
#define TK_INTO                           29
#define TK_IS                             30
#define TK_ISNULL                         31
#define TK_KEY                            32
#define TK_LE                             33
#define TK_LP                             34
#define TK_LT                             35
#define TK_MINUS                          36
#define TK_NE                             37
#define TK_NOT                            38
#define TK_NOTNULL                        39
#define TK_NULL                           40
#define TK_ON                             41
#define TK_OR                             42
#define TK_ORDER                          43
#define TK_PERCENT                        44
#define TK_PLUS                           45
#define TK_PRIMARY                        46
#define TK_RP                             47
#define TK_SELECT                         48
#define TK_SEMI                           49
#define TK_SET                            50
#define TK_SLASH                          51
#define TK_SPACE                          52
#define TK_STAR                           53
#define TK_STRING                         54
#define TK_TABLE                          55
#define TK_UMINUS                         56
#define TK_UNCLOSED_STRING                57
#define TK_UNIQUE                         58
#define TK_UPDATE                         59
#define TK_VALUES                         60
#define TK_WHERE                          61
